site_name: Samuel Aytenfsu | Knowledge Platform
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy

nav:
  - Home: index.md
  - Skills Comparison: comparisons.md
  - Projects:
      - Sales Forecasting: projects/sales.md
  - Certifications: certifications.md
  - Technical Notes:
      - Fabric Lakehouse: Notes/fabric-lakehouse.md
      - Semantic Model: "Notes/Semantic Model (Power BI  Fabric).md"
      - Vector Embedding: Notes/Vector Embedding.md

plugins:
  - search:
      separator: '[\s\-\.]+'

extra:
  generator: false